name: flutter_inappwebview_nsg_fix
description: A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.
version: 6.2.0-beta.3
homepage: https://inappwebview.dev/
repository: https://github.com/pichillilorenzo/flutter_inappwebview
issue_tracker: https://github.com/pichillilorenzo/flutter_inappwebview/issues
funding:
  - https://inappwebview.dev/donate/
topics:
  - html
  - webview
  - webview-flutter
  - inappwebview
  - browser

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview_platform_interface_nsg_fix:
    path: ../flutter_inappwebview_platform_interface
  flutter_inappwebview_android_nsg_fix:
    path: ../flutter_inappwebview_android
  flutter_inappwebview_ios_nsg_fix:
    path: ../flutter_inappwebview_ios
  flutter_inappwebview_macos_nsg_fix:
    path: ../flutter_inappwebview_macos
  flutter_inappwebview_web_nsg_fix:
    path: ../flutter_inappwebview_web
  flutter_inappwebview_windows_nsg_fix:
    path: ../flutter_inappwebview_windows
  flutter_inappwebview_linux_nsg_fix:
    path: ../flutter_inappwebview_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  generators:
    path: ../dev_packages/generators

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_inappwebview_android_nsg_fix
      ios:
        default_package: flutter_inappwebview_ios_nsg_fix
      macos:
        default_package: flutter_inappwebview_macos_nsg_fix
      web:
        default_package: flutter_inappwebview_web_nsg_fix
      windows:
        default_package: flutter_inappwebview_windows_nsg_fix
      linux:
        default_package: flutter_inappwebview_linux_nsg_fix

  assets:
    - packages/flutter_inappwebview_nsg_fix/assets/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview_nsg_fix/assets/t_rex_runner/t-rex.css
